<?php

namespace QuizzBundle\Repository;

use QuizzBundle\Data\SearchData;
use QuizzBundle\Form\ProduitsSearchType;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLastProducts()
    {
        return $this->createQueryBuilder('p')
            ->addOrderBy('p.date', 'DESC')
            ->getQuery()
            ->execute();
    }

    public function findProductsByUser($user)
    {
        $query=$this->createQueryBuilder('p')
            ->leftJoin('p.user', 'u')
            ->where('u.id=:userid')
            ->setParameter('userid',$user->getId())
            ->addOrderBy('p.nom', 'ASC')
            ->getQuery()
            ->getResult();

        return $query;
    }

    public function findSearch( $search)
    {
        $query = $this
            ->createQueryBuilder('p');
            //->select('categorie', 'produits');
            //->join('p.categories', 'c');
        if(!empty($search["q"])){
            $query = $query
            ->andWhere("p.nom LIKE '%".$search["q"]."%'");
        }
        if (!empty($search["categorie"])) {
            $query = $query
                ->andWhere('p.categories = :categorie')
                ->setParameter('categorie', $search["categorie"]);
        }
        return $query->getQuery()->getResult();

    }


    public function findByCategory($categoryId, $search) {
        return $this->findBy(['categories' => $categoryId]);
    }
}
